# Generated by Django 5.1.6 on 2025-03-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('description', models.TextField(db_column='description', null=True)),
            ],
            options={
                'db_table': 'Category',
                'ordering': ['-id'],
            },
        ),
    ]
