# Generated by Django 5.1.6 on 2025-03-05 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_column='quantity', default=None, null=True)),
                ('description', models.TextField(db_column='description', null=True)),
                ('price', models.IntegerField(db_column='price')),
                ('weight', models.FloatField(db_column='weight', null=True)),
                ('weight_unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('ml', 'ml')], db_column='weight_unit', default=None, max_length=5, null=True)),
                ('date', models.DateField(db_column='date')),
                ('item', models.ForeignKey(db_column='item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
            options={
                'db_table': 'Expense',
                'ordering': ['-id'],
            },
        ),
    ]
