# Generated by Django 5.1.6 on 2025-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='weight',
            field=models.FloatField(db_column='weight', default=None, null=True),
        ),
    ]
